services:
  pipeline:
    build: .
    container_name: transit_delay_analytics
    # Ensures that when the computer is restarted, the script will run again
    restart: unless-stopped 
    environment:
      - TZ=UTC
    volumes:
      # Maps Windows directories (left) to container directories (right)
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config